# This is a localhost development configuration for this service
version: '3.4'

services:
  tynabot:
    restart: "no"
    container_name:  tynabot
    image: tynabot:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app

  nginx:
    restart: "no"
    container_name: tynabot_nginx 
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - tynabot